import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { after, test } from "node:test";
import { createServer } from "../src/server.mjs";
import { TripGroupError } from "../src/trip-group-store.mjs";

const now=()=>new Date().toISOString(),hash=x=>createHash("sha256").update(x).digest("hex");
const users={owner:{email:"owner@example.com",displayName:"Owner",avatarUrl:"owner.png"},editor:{email:"editor@example.com",displayName:"Editor",avatarUrl:"editor.png"},viewer:{email:"viewer@example.com",displayName:"Viewer",avatarUrl:""},wrong:{email:"wrong@example.com",displayName:"Wrong",avatarUrl:""}};
class MemoryTripGroups{
 constructor(){this.groups=new Map();this.invites=new Map();this.audit=[];}
 view(user,id){const g=this.groups.get(id);if(!g||!g.members.has(user))throw new TripGroupError(404,"NOT_FOUND","Trip group not found");const role=g.members.get(user).role,members=[...g.members].map(([userId,m])=>({userId,displayName:users[userId].displayName,avatarUrl:users[userId].avatarUrl,role:m.role,acceptedAt:m.acceptedAt}));const out={id:g.id,clientTripId:g.clientTripId,title:g.title,startDate:g.startDate,endDate:g.endDate,revision:g.revision,content:g.content,role,createdAt:g.createdAt,updatedAt:g.updatedAt,members};if(role==="OWNER")out.invitations=[...this.invites.values()].filter(i=>i.groupId===id&&i.status==="PENDING"&&new Date(i.expiresAt)>new Date()).map(({tokenHash,groupId,invitedBy,...i})=>i);return out;}
 async create(user,x){const old=[...this.groups.values()].find(g=>g.owner===user&&(g.clientTripId===x.clientTripId||g.key===x.idempotencyKey));if(old)return this.view(user,old.id);const id=randomUUID(),stamp=now();this.groups.set(id,{...x,id,owner:user,revision:1,createdAt:stamp,updatedAt:stamp,members:new Map([[user,{role:"OWNER",acceptedAt:stamp}]])});this.audit.push({actor:user,action:"GROUP_CREATED",at:stamp});return this.view(user,id);}
 async list(user){return[...this.groups.values()].filter(g=>g.members.has(user)).map(g=>this.view(user,g.id));}async get(user,id){return this.view(user,id);}
 async deleteGroup(user,id){const g=this.groups.get(id);if(this.view(user,id).role!=="OWNER"||g.owner!==user)throw new TripGroupError(404,"NOT_FOUND","Trip group not found");this.groups.delete(id);for(const[inviteId,invite]of this.invites)if(invite.groupId===id)this.invites.delete(inviteId);return{deleted:true};}
 async updateSnapshot(user,id,revision,content){const g=this.groups.get(id);this.view(user,id);const role=g.members.get(user).role;if(!["OWNER","EDITOR"].includes(role))throw new TripGroupError(403,"FORBIDDEN","Write access required");if(g.revision!==revision)throw new TripGroupError(409,"REVISION_CONFLICT","Snapshot revision has changed",{serverRevision:g.revision});g.content=content;g.revision++;g.updatedAt=now();return this.view(user,id);}
 async createInvitation(user,id,x){const g=this.groups.get(id),view=this.view(user,id);if(view.role!=="OWNER")throw new TripGroupError(404,"NOT_FOUND","Trip group not found");const token=`token-${randomUUID()}`,inv={id:randomUUID(),groupId:id,invitedBy:user,tokenHash:hash(token),email:x.email,displayName:x.displayName,role:x.role,status:"PENDING",expiresAt:new Date(Date.now()+604800000).toISOString(),createdAt:now()};this.invites.set(inv.id,inv);return{invitation:{id:inv.id,email:inv.email,displayName:inv.displayName,role:inv.role,status:inv.status,expiresAt:inv.expiresAt,createdAt:inv.createdAt},token,groupTitle:g.title};}
 async deliveryFailed(user,id,invitationId){this.invites.get(invitationId).status="DELIVERY_FAILED";}
 async revoke(user,id,invitationId){if(this.view(user,id).role!=="OWNER")throw new TripGroupError(404,"NOT_FOUND","Trip group not found");const i=this.invites.get(invitationId);if(!i||i.groupId!==id||i.status!=="PENDING")throw new TripGroupError(404,"NOT_FOUND","Invitation not found");i.status="REVOKED";return{revoked:true};}
 async resolveInvitation(user,token,accepted){const i=[...this.invites.values()].find(x=>x.tokenHash===hash(token));if(!i)throw new TripGroupError(404,"NOT_FOUND","Invitation not found");if(i.email!==users[user].email)throw new TripGroupError(403,"EMAIL_MISMATCH","Invitation belongs to another account");if(new Date(i.expiresAt)<=new Date()){i.status="EXPIRED";throw new TripGroupError(410,"INVITATION_EXPIRED","Invitation has expired");}const target=accepted?"ACCEPTED":"DECLINED";if(i.status===target)return accepted?this.view(user,i.groupId):{status:target};if(i.status!=="PENDING")throw new TripGroupError(409,"INVITATION_UNAVAILABLE","Invitation unavailable");i.status=target;if(accepted){i.acceptedBy=user;this.groups.get(i.groupId).members.set(user,{role:i.role,acceptedAt:now()});return this.view(user,i.groupId);}return{status:target};}
 async changeRole(user,id,member,role){const g=this.groups.get(id);if(this.view(user,id).role!=="OWNER")throw new TripGroupError(404,"NOT_FOUND","Trip group not found");if(member===g.owner)throw new TripGroupError(409,"OWNER_REQUIRED","Primary owner role cannot be changed");if(!g.members.has(member))throw new TripGroupError(404,"NOT_FOUND","Member not found");g.members.get(member).role=role;return{userId:member,role};}
 async removeMember(user,id,member){const g=this.groups.get(id);if(this.view(user,id).role!=="OWNER")throw new TripGroupError(404,"NOT_FOUND","Trip group not found");if(member===g.owner)throw new TripGroupError(409,"OWNER_REQUIRED","Primary owner cannot be removed");if(!g.members.delete(member))throw new TripGroupError(404,"NOT_FOUND","Member not found");return{removed:true};}
 async leave(user,id){const g=this.groups.get(id),v=this.view(user,id);if(v.role==="OWNER")throw new TripGroupError(409,"OWNER_REQUIRED","Last owner cannot leave");g.members.delete(user);return{left:true};}
}
const content=(name="Champagnereis")=>({name,startDate:"2026-09-01",endDate:"2026-09-03",houseIds:["ruinart"],houseDates:{ruinart:"2026-09-01"},houseTimes:{ruinart:"10:00"},events:[{id:"e1",title:"Diner",location:"Reims",startsAt:null,endsAt:null,plannedDate:"2026-09-01",plannedTime:"19:00",latitude:49.25,longitude:4.03}]});
async function environment(run){const store=new MemoryTripGroups(),mails=[];const server=createServer({tripGroupStore:store,tripInviteMailer:async x=>mails.push(x),authenticateSlice2:req=>{const id=String(req.headers.authorization||"").replace(/^Bearer /,"");return id?{sub:id}:null;}}).listen(0,"127.0.0.1");await new Promise(r=>server.once("listening",r));try{await run(`http://127.0.0.1:${server.address().port}`,store,mails);}finally{await new Promise(r=>server.close(r));}}
const call=(base,path,user,method="GET",body)=>fetch(base+path,{method,headers:{...(user?{Authorization:`Bearer ${user}`}:{ }),...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});
async function create(base){return(await call(base,"/api/v1/trip-groups","owner","POST",{clientTripId:randomUUID(),title:"Herfstreis",startDate:"2026-09-01",endDate:"2026-09-03",content:content(),idempotencyKey:randomUUID()})).json();}

test("trip groups require auth and private responses are never cached",()=>environment(async base=>{const r=await call(base,"/api/v1/trip-groups",null);assert.equal(r.status,401);assert.equal(r.headers.get("cache-control"),"private, no-store");}));
test("only owner can delete a trip group and deletion is final",()=>environment(async base=>{const group=await create(base);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}`,"wrong","DELETE")).status,404);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}`,"owner","DELETE")).status,200);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}`,"owner")).status,404);}));
test("owner creates and invites with hashed one-use token",()=>environment(async(base,store,mails)=>{const group=await create(base);const response=await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:"EDITOR@EXAMPLE.COM",displayName:"Ed",role:"EDITOR"});assert.equal(response.status,201);assert.equal(mails.length,1);const stored=[...store.invites.values()][0];assert.equal(stored.tokenHash,hash(mails[0].token));assert.equal(JSON.stringify(stored).includes(mails[0].token),false);assert.equal((await call(base,"/api/v1/trip-invitations/accept","wrong","POST",{token:mails[0].token})).status,403);const accepted=await call(base,"/api/v1/trip-invitations/accept","editor","POST",{token:mails[0].token});assert.equal(accepted.status,200);assert.equal((await call(base,"/api/v1/trip-invitations/accept","editor","POST",{token:mails[0].token})).status,200);}));
test("accepted members see snapshot and members but never invitation emails",()=>environment(async(base,store,mails)=>{const group=await create(base);await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:"editor@example.com",role:"EDITOR"});await call(base,"/api/v1/trip-invitations/accept","editor","POST",{token:mails[0].token});const member=await(await call(base,`/api/v1/trip-groups/${group.id}`,"editor")).json();assert.equal(member.content.name,"Champagnereis");assert.equal(member.members.length,2);assert.equal("invitations" in member,false);assert.equal(JSON.stringify(member).includes("owner@example.com"),false);const owner=await(await call(base,`/api/v1/trip-groups/${group.id}`,"owner")).json();assert.ok(Array.isArray(owner.invitations));}));
test("viewer cannot write; editor updates optimistically and conflict is 409",()=>environment(async(base,store,mails)=>{const group=await create(base);for(const [id,role] of [["editor","EDITOR"],["viewer","VIEWER"]]){await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:users[id].email,role});await call(base,"/api/v1/trip-invitations/accept",id,"POST",{token:mails.at(-1).token});}assert.equal((await call(base,`/api/v1/trip-groups/${group.id}/snapshot`,"viewer","PUT",{revision:1,content:content("Nope")})).status,403);const ok=await call(base,`/api/v1/trip-groups/${group.id}/snapshot`,"editor","PUT",{revision:1,content:content("Nieuw")});assert.equal(ok.status,200);const conflict=await call(base,`/api/v1/trip-groups/${group.id}/snapshot`,"editor","PUT",{revision:1,content:content("Oud")});assert.equal(conflict.status,409);assert.equal((await conflict.json()).error.details.serverRevision,2);}));
test("revoke, decline, expiry, remove and leave rules",()=>environment(async(base,store,mails)=>{const group=await create(base);let r=await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:"viewer@example.com",role:"VIEWER"});let invitation=(await r.json()).invitation;assert.equal((await call(base,`/api/v1/trip-groups/${group.id}/invitations/${invitation.id}`,"owner","DELETE")).status,200);await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:"viewer@example.com",role:"VIEWER"});assert.equal((await call(base,"/api/v1/trip-invitations/decline","viewer","POST",{token:mails.at(-1).token})).status,200);await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:"editor@example.com",role:"EDITOR"});store.invites.get([...store.invites.keys()].at(-1)).expiresAt="2020-01-01T00:00:00Z";assert.equal((await call(base,"/api/v1/trip-invitations/accept","editor","POST",{token:mails.at(-1).token})).status,410);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}/members/me`,"owner","DELETE")).status,409);}));
test("owner changes roles/removes members and a member can leave",()=>environment(async(base,store,mails)=>{const group=await create(base);for(const id of ["editor","viewer"]){await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:users[id].email,role:"EDITOR"});await call(base,"/api/v1/trip-invitations/accept",id,"POST",{token:mails.at(-1).token});}let changed=await call(base,`/api/v1/trip-groups/${group.id}/members/editor`,"owner","PATCH",{role:"VIEWER"});assert.equal(changed.status,200);assert.equal((await changed.json()).role,"VIEWER");assert.equal((await call(base,`/api/v1/trip-groups/${group.id}/members/viewer`,"owner","DELETE")).status,200);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}`,"viewer")).status,404);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}/members/me`,"editor","DELETE")).status,200);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}`,"editor")).status,404);}));
test("mail failure marks invitation non-pending",async()=>{const store=new MemoryTripGroups();const server=createServer({tripGroupStore:store,tripInviteMailer:async()=>{throw new Error("mail unavailable");},authenticateSlice2:req=>({sub:String(req.headers.authorization||"").replace(/^Bearer /,"")})}).listen(0,"127.0.0.1");await new Promise(r=>server.once("listening",r));const base=`http://127.0.0.1:${server.address().port}`;try{const group=await create(base);const response=await call(base,`/api/v1/trip-groups/${group.id}/invitations`,"owner","POST",{email:"editor@example.com",role:"EDITOR"});assert.equal(response.status,502);assert.equal([...store.invites.values()][0].status,"DELIVERY_FAILED");assert.equal((await(await call(base,`/api/v1/trip-groups/${group.id}`,"owner")).json()).invitations.length,0);}finally{await new Promise(r=>server.close(r));}});
test("cross-user access is concealed as 404 and public invite redirect exposes no metadata",()=>environment(async base=>{const group=await create(base);assert.equal((await call(base,`/api/v1/trip-groups/${group.id}`,"wrong")).status,404);const redirect=await fetch(`${base}/auth/trip-invite?token=opaque`,{redirect:"manual"});assert.equal(redirect.status,302);assert.equal(redirect.headers.get("location"),"nl.champagneatlas://trip-invite?token=opaque");assert.equal(redirect.headers.get("cache-control"),"no-store");}));
test("shared cover images are accepted within the private snapshot limit",()=>environment(async base=>{const payload=content();payload.coverImageData="YWJj";const response=await call(base,"/api/v1/trip-groups","owner","POST",{clientTripId:randomUUID(),title:"Fotoreis",startDate:"2026-09-01",endDate:"2026-09-03",content:payload,idempotencyKey:randomUUID()});assert.equal(response.status,201);assert.equal((await response.json()).content.coverImageData,"YWJj");payload.coverImageData="A".repeat(180001);const invalid=await call(base,"/api/v1/trip-groups","owner","POST",{clientTripId:randomUUID(),title:"Te groot",content:payload,idempotencyKey:randomUUID()});assert.equal(invalid.status,400);}));

after(()=>{});
