BEGIN;
DROP TABLE IF EXISTS house_submissions;
DELETE FROM notification_inbox WHERE type LIKE 'HOUSE_SUBMISSION_%';
ALTER TABLE notification_inbox DROP CONSTRAINT IF EXISTS notification_inbox_type_check;
ALTER TABLE notification_inbox ADD CONSTRAINT notification_inbox_type_check CHECK (type IN (
  'TRIP_ACTIVITY_ADDED','TRIP_ACTIVITY_UPDATED','TRIP_ACTIVITY_REMOVED',
  'TRIP_DETAILS_UPDATED','TRIP_SNAPSHOT_UPDATED','TRIP_GROUP_ACTIVITY_BUNDLE',
  'TRIP_INVITATION_ACCEPTED','TRIP_INVITATION_DECLINED',
  'TRIP_MEMBER_ROLE_CHANGED','TRIP_MEMBER_REMOVED','TRIP_MEMBER_LEFT',
  'TRIP_REMINDER','TRIP_EVENT_UPDATE'
));
COMMIT;
