// Generated by sync-open-data.mjs; do not edit manually.
// OpenStreetMap data © OpenStreetMap contributors, available under ODbL.
export const openDataProducers = [
  {
    "id": "osm-node-9481414066",
    "name": "Champagne A. Viot et Fils",
    "normalizedName": "a-viot-et-fils",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "67 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne A. Viot et Fils is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-viot.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9481414066",
    "initials": "AV",
    "accent": "FF55766F",
    "latitude": 48.2645421,
    "longitude": 4.7887645,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9510850930",
    "name": "Champagne Alain Beau",
    "normalizedName": "alain-beau",
    "type": "GROWER",
    "city": "Voigny",
    "address": "Place Sainte-Affre, 10200, Voigny",
    "region": "Côte des Bar",
    "description": "Champagne Alain Beau is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://beaualain.site-solocal.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9510850930",
    "initials": "AB",
    "accent": "FF55766F",
    "latitude": 48.240979,
    "longitude": 4.7687162,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9503012781",
    "name": "Champagne Alain Leboeuf",
    "normalizedName": "alain-leboeuf",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "1 Rue du Moulin, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Alain Leboeuf is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-alain-leboeuf.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/9503012781",
    "initials": "AL",
    "accent": "FF55766F",
    "latitude": 48.2635796,
    "longitude": 4.7900614,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1026416923",
    "name": "Champagne Albert Beerens",
    "normalizedName": "albert-beerens",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "37 Rue Blanche, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Albert Beerens is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://www.champagnebeerens.com/",
    "directoryUrl": "https://www.openstreetmap.org/way/1026416923",
    "initials": "AB",
    "accent": "FF55766F",
    "latitude": 48.2653801,
    "longitude": 4.7470579,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1012807599",
    "name": "Champagne Alfred Gratien",
    "normalizedName": "alfred-gratien",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Alfred Gratien is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/1012807599",
    "initials": "AG",
    "accent": "FF55766F",
    "latitude": 49.038831,
    "longitude": 3.9610607,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-13144424257",
    "name": "Champagne B.Girardin",
    "normalizedName": "b-girardin",
    "type": "GROWER",
    "city": "Mancy",
    "address": "14 Grande Rue, 51530, Mancy",
    "region": "Montagne de Reims",
    "description": "Champagne B.Girardin is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-bgirardin.com",
    "directoryUrl": "https://www.openstreetmap.org/node/13144424257",
    "initials": "B",
    "accent": "FF55766F",
    "latitude": 48.9825144,
    "longitude": 3.9342064,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9510850932",
    "name": "Champagne Bernard Robert",
    "normalizedName": "bernard-robert",
    "type": "GROWER",
    "city": "Voigny",
    "address": "22 Rue de l'Orme, 10200, Voigny",
    "region": "Côte des Bar",
    "description": "Champagne Bernard Robert is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnebernardrobert.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9510850932",
    "initials": "BR",
    "accent": "FF55766F",
    "latitude": 48.2397947,
    "longitude": 4.7649866,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-7798374497",
    "name": "Champagne Betouzet-Brugneau",
    "normalizedName": "betouzet-brugneau",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Vallée de la Marne",
    "description": "Champagne Betouzet-Brugneau is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-betouzet.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/7798374497",
    "initials": "BB",
    "accent": "FF55766F",
    "latitude": 49.0828604,
    "longitude": 3.6580704,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11418699434",
    "name": "Champagne Bonnevie - Bocart",
    "normalizedName": "bonnevie-bocart",
    "type": "GROWER",
    "city": "Billy le grand",
    "address": "10 Rue du midi, 51400, Billy le grand",
    "region": "Montagne de Reims",
    "description": "Champagne Bonnevie - Bocart is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-bonnevie-bocart.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/11418699434",
    "initials": "BB",
    "accent": "FF55766F",
    "latitude": 49.1078686,
    "longitude": 4.2297752,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1027048351",
    "name": "Champagne Boulachin Chaput",
    "normalizedName": "boulachin-chaput",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "21 Rue Michelot, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Boulachin Chaput is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagneboulachin.com/",
    "directoryUrl": "https://www.openstreetmap.org/way/1027048351",
    "initials": "BC",
    "accent": "FF55766F",
    "latitude": 48.2660244,
    "longitude": 4.7424086,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-7133445748",
    "name": "Champagne Caillez-Lemaire",
    "normalizedName": "caillez-lemaire",
    "type": "GROWER",
    "city": "Damery",
    "address": "14 Rue Pierre Curie, 51480, Damery",
    "region": "Montagne de Reims",
    "description": "Champagne Caillez-Lemaire is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-caillez-lemaire.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/7133445748",
    "initials": "CL",
    "accent": "FF55766F",
    "latitude": 49.068908,
    "longitude": 3.8823615,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9483077660",
    "name": "Champagne Camille Courteaux",
    "normalizedName": "camille-courteaux",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "9 Rue des Moulins, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Camille Courteaux is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-courteaux.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/9483077660",
    "initials": "CC",
    "accent": "FF55766F",
    "latitude": 48.2619602,
    "longitude": 4.7441223,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-12989518201",
    "name": "Champagne Canard-Duchêne",
    "normalizedName": "canard-duchene",
    "type": "GROWER",
    "city": "Champagne",
    "address": "1 Rue Edmond Canard, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Canard-Duchêne is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/12989518201",
    "initials": "CD",
    "accent": "FF55766F",
    "latitude": 49.1545867,
    "longitude": 4.0820988,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-relation-1304669",
    "name": "Champagne Charles Cazanove",
    "normalizedName": "charles-cazanove",
    "type": "GROWER",
    "city": "Champagne",
    "address": "8, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Charles Cazanove is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnedecazanove.com/fr/index.php",
    "directoryUrl": "https://www.openstreetmap.org/relation/1304669",
    "initials": "CC",
    "accent": "FF55766F",
    "latitude": 49.2618552,
    "longitude": 4.0281735,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1030408474",
    "name": "Champagne Charles Clement",
    "normalizedName": "charles-clement",
    "type": "COOPERATIVE",
    "city": "Colombé-le-Sec",
    "address": "33 Rue Saint-Antoine, 10200, Colombé-le-Sec",
    "region": "Côte des Bar",
    "description": "Champagne Charles Clement is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-charles-clement.fr/",
    "directoryUrl": "https://www.openstreetmap.org/way/1030408474",
    "initials": "CC",
    "accent": "FF55766F",
    "latitude": 48.2524957,
    "longitude": 4.7971228,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9503012783",
    "name": "Champagne Christien Thiebaut",
    "normalizedName": "christien-thiebaut",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "40 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Christien Thiebaut is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9503012783",
    "initials": "CT",
    "accent": "FF55766F",
    "latitude": 48.2644652,
    "longitude": 4.7863096,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9498323115",
    "name": "Champagne Christophe",
    "normalizedName": "christophe",
    "type": "GROWER",
    "city": "Colombé-le-Sec",
    "address": "16 Rue Saint-Antoine, 10200, Colombé-le-Sec",
    "region": "Côte des Bar",
    "description": "Champagne Christophe is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-christophe.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9498323115",
    "initials": "C",
    "accent": "FF55766F",
    "latitude": 48.2566875,
    "longitude": 4.7952211,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-12395496414",
    "name": "Champagne Cottet-Dubreuil",
    "normalizedName": "cottet-dubreuil",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Cottet-Dubreuil is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://cottet-dubreuil.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/12395496414",
    "initials": "CD",
    "accent": "FF55766F",
    "latitude": 48.0187326,
    "longitude": 4.4454892,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9505317525",
    "name": "Champagne Courtillion Line et Fils",
    "normalizedName": "courtillion-line-et-fils",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "7 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Courtillion Line et Fils is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9505317525",
    "initials": "CL",
    "accent": "FF55766F",
    "latitude": 48.2626596,
    "longitude": 4.7830511,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400007758",
    "name": "Champagne Daniel Dumont",
    "normalizedName": "daniel-dumont",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Daniel Dumont is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400007758",
    "initials": "DD",
    "accent": "FF55766F",
    "latitude": 49.1669955,
    "longitude": 4.0424118,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-7658625942",
    "name": "Champagne Delagarde Delozanne",
    "normalizedName": "delagarde-delozanne",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Delagarde Delozanne is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/7658625942",
    "initials": "DD",
    "accent": "FF55766F",
    "latitude": 49.2514432,
    "longitude": 3.7673655,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9463332349",
    "name": "Champagne Denis Chaput",
    "normalizedName": "denis-chaput",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "8 Rue de la Souche, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Denis Chaput is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-denischaput.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9463332349",
    "initials": "DC",
    "accent": "FF55766F",
    "latitude": 48.2639375,
    "longitude": 4.7437497,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-13050177166",
    "name": "Champagne Didier Ducos",
    "normalizedName": "didier-ducos",
    "type": "GROWER",
    "city": "Champagne",
    "address": "9 bis Rue Julien Ducos, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Didier Ducos is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/13050177166",
    "initials": "DD",
    "accent": "FF55766F",
    "latitude": 49.0130385,
    "longitude": 3.877234,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-7508518298",
    "name": "Champagne DRAPPIER",
    "normalizedName": "drappier",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne DRAPPIER is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://www.champagne-drappier.com/fr",
    "directoryUrl": "https://www.openstreetmap.org/node/7508518298",
    "initials": "D",
    "accent": "FF55766F",
    "latitude": 49.245721,
    "longitude": 4.0456983,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181435875",
    "name": "Champagne Fourrier",
    "normalizedName": "fourrier",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Fourrier is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10181435875",
    "initials": "F",
    "accent": "FF55766F",
    "latitude": 48.1963563,
    "longitude": 4.7250491,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400016459",
    "name": "Champagne François Fagot",
    "normalizedName": "francois-fagot",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne François Fagot is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400016459",
    "initials": "FF",
    "accent": "FF55766F",
    "latitude": 49.1677412,
    "longitude": 4.0443768,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9505317528",
    "name": "Champagne Frédéric Tapray",
    "normalizedName": "frederic-tapray",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "6 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Frédéric Tapray is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-frederictapray.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/9505317528",
    "initials": "FT",
    "accent": "FF55766F",
    "latitude": 48.2612418,
    "longitude": 4.782064,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9503012782",
    "name": "Champagne Germar Breton",
    "normalizedName": "germar-breton",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "19 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Germar Breton is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-germar-breton.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9503012782",
    "initials": "GB",
    "accent": "FF55766F",
    "latitude": 48.2637305,
    "longitude": 4.7830574,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-649114363",
    "name": "Champagne Gounel Lassalle",
    "normalizedName": "gounel-lassalle",
    "type": "GROWER",
    "city": "Chigny-les-Roses",
    "address": "6 Rue Jobert, 51500, Chigny-les-Roses",
    "region": "Montagne de Reims",
    "description": "Champagne Gounel Lassalle is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-gounel-lassalle.fr",
    "directoryUrl": "https://www.openstreetmap.org/way/649114363",
    "initials": "GL",
    "accent": "FF55766F",
    "latitude": 49.156316,
    "longitude": 4.0612383,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9501078096",
    "name": "Champagne Guillaume Phelizot",
    "normalizedName": "guillaume-phelizot",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "6 Ruelle du Clos, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Guillaume Phelizot is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-phelizot.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9501078096",
    "initials": "GP",
    "accent": "FF55766F",
    "latitude": 48.2646574,
    "longitude": 4.743889,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9481414067",
    "name": "Champagne Guy Bertrand",
    "normalizedName": "guy-bertrand",
    "type": "GROWER",
    "city": "Voigny",
    "address": "14 Rue de l'Orme, 10200, Voigny",
    "region": "Côte des Bar",
    "description": "Champagne Guy Bertrand is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9481414067",
    "initials": "GB",
    "accent": "FF55766F",
    "latitude": 48.2399888,
    "longitude": 4.7659824,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400128310",
    "name": "Champagne Henri Chauvet",
    "normalizedName": "henri-chauvet",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Henri Chauvet is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400128310",
    "initials": "HC",
    "accent": "FF55766F",
    "latitude": 49.1657696,
    "longitude": 4.0455718,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-3504788070",
    "name": "Champagne Henri Lemaire-Fourny",
    "normalizedName": "henri-lemaire-fourny",
    "type": "GROWER",
    "city": "Damery",
    "address": "13 Rue Raymond Poincaré, 51480, Damery",
    "region": "Montagne de Reims",
    "description": "Champagne Henri Lemaire-Fourny is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/3504788070",
    "initials": "HL",
    "accent": "FF55766F",
    "latitude": 49.0702588,
    "longitude": 3.8788388,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6997051530",
    "name": "Champagne Hotte-Schmit",
    "normalizedName": "hotte-schmit",
    "type": "GROWER",
    "city": "Brimont",
    "address": "8 Rue des Orfèvres, 51220, Brimont",
    "region": "Montagne de Reims",
    "description": "Champagne Hotte-Schmit is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://hotte-schmit.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/6997051530",
    "initials": "HS",
    "accent": "FF55766F",
    "latitude": 49.34217,
    "longitude": 4.0233631,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9507869237",
    "name": "Champagne Hubert Boulachin",
    "normalizedName": "hubert-boulachin",
    "type": "GROWER",
    "city": "Colombé-le-Sec",
    "address": "1 Les Cleuselots, 10200, Colombé-le-Sec",
    "region": "Côte des Bar",
    "description": "Champagne Hubert Boulachin is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9507869237",
    "initials": "HB",
    "accent": "FF55766F",
    "latitude": 48.2533259,
    "longitude": 4.7961936,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6610943870",
    "name": "Champagne Hubert Thiébault",
    "normalizedName": "hubert-thiebault",
    "type": "GROWER",
    "city": "Montgenost",
    "address": "1 Rue de la Tourelle, 51260, Montgenost",
    "region": "Vallée de la Marne",
    "description": "Champagne Hubert Thiébault is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-hubert-thiebault.fr",
    "directoryUrl": "https://www.openstreetmap.org/node/6610943870",
    "initials": "HT",
    "accent": "FF55766F",
    "latitude": 48.5962927,
    "longitude": 3.5952398,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400128190",
    "name": "Champagne J.&H. Fagot",
    "normalizedName": "j-and-h-fagot",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne J.&H. Fagot is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400128190",
    "initials": "JH",
    "accent": "FF55766F",
    "latitude": 49.1670355,
    "longitude": 4.0470663,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1027048350",
    "name": "Champagne Jacques Chaput",
    "normalizedName": "jacques-chaput",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "1 Rue Blanche, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Jacques Chaput is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.jacques-chaput.fr/",
    "directoryUrl": "https://www.openstreetmap.org/way/1027048350",
    "initials": "JC",
    "accent": "FF55766F",
    "latitude": 48.2601945,
    "longitude": 4.7386642,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11502658224",
    "name": "Champagne Jacquesson",
    "normalizedName": "jacquesson",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Jacquesson is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnejacquesson.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/11502658224",
    "initials": "J",
    "accent": "FF55766F",
    "latitude": 49.0652928,
    "longitude": 3.9658163,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9505317526",
    "name": "Champagne Jacquinot et Fils",
    "normalizedName": "jacquinot-et-fils",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "4 Rue d'Escurez, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Jacquinot et Fils is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9505317526",
    "initials": "JE",
    "accent": "FF55766F",
    "latitude": 48.2639265,
    "longitude": 4.7911058,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6652083036",
    "name": "Champagne Jean Seleque",
    "normalizedName": "jean-seleque",
    "type": "GROWER",
    "city": "Pierry",
    "address": "12 Rue de l'Égalité, 51530, Pierry",
    "region": "Montagne de Reims",
    "description": "Champagne Jean Seleque is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://champagne-jean-seleque.net",
    "directoryUrl": "https://www.openstreetmap.org/node/6652083036",
    "initials": "JS",
    "accent": "FF55766F",
    "latitude": 49.0161441,
    "longitude": 3.9423215,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-12444827915",
    "name": "Champagne Jean-François Launay",
    "normalizedName": "jean-francois-launay",
    "type": "GROWER",
    "city": "Venteuil",
    "address": "Route de Venteuil, 51480, Venteuil",
    "region": "Montagne de Reims",
    "description": "Champagne Jean-François Launay is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-jean-francois-launay.fr",
    "directoryUrl": "https://www.openstreetmap.org/node/12444827915",
    "initials": "JF",
    "accent": "FF55766F",
    "latitude": 49.0809694,
    "longitude": 3.8544468,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6948681625",
    "name": "Champagne Jean-Guy Viot",
    "normalizedName": "jean-guy-viot",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Jean-Guy Viot is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/6948681625",
    "initials": "JG",
    "accent": "FF55766F",
    "latitude": 48.240004,
    "longitude": 4.8245227,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-7798388401",
    "name": "Champagne Jeandon",
    "normalizedName": "jeandon",
    "type": "GROWER",
    "city": "Champagne",
    "address": "1 Place Saint-Pothin, Champagne",
    "region": "Vallée de la Marne",
    "description": "Champagne Jeandon is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-jeandon.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/7798388401",
    "initials": "J",
    "accent": "FF55766F",
    "latitude": 49.080249,
    "longitude": 3.6600915,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400128428",
    "name": "Champagne Jeangout",
    "normalizedName": "jeangout",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Jeangout is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnejeangout.com/",
    "directoryUrl": "https://www.openstreetmap.org/way/400128428",
    "initials": "J",
    "accent": "FF55766F",
    "latitude": 49.1663832,
    "longitude": 4.0456695,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400128447",
    "name": "Champagne Julien Herbert",
    "normalizedName": "julien-herbert",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Julien Herbert is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400128447",
    "initials": "JH",
    "accent": "FF55766F",
    "latitude": 49.1657454,
    "longitude": 4.0453504,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-636129443",
    "name": "Champagne Launois Père et Fils",
    "normalizedName": "launois-pere-et-fils",
    "type": "GROWER",
    "city": "Champagne",
    "address": "2 Avenue Eugène Guillaume, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Launois Père et Fils is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/636129443",
    "initials": "LP",
    "accent": "FF55766F",
    "latitude": 48.9486953,
    "longitude": 4.025118,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9481414068",
    "name": "Champagne Laurent Courtillier",
    "normalizedName": "laurent-courtillier",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "15 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Laurent Courtillier is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://champagne-laurent-courtillier.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/9481414068",
    "initials": "LC",
    "accent": "FF55766F",
    "latitude": 48.2632474,
    "longitude": 4.7829283,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181412372",
    "name": "Champagne Laurent Etienne",
    "normalizedName": "laurent-etienne",
    "type": "GROWER",
    "city": "Champagne",
    "address": "2 Route de Bligny, Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Laurent Etienne is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-laurent-etienne.com",
    "directoryUrl": "https://www.openstreetmap.org/node/10181412372",
    "initials": "LE",
    "accent": "FF55766F",
    "latitude": 48.201697,
    "longitude": 4.6300899,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11417742257",
    "name": "Champagne Le Gouive",
    "normalizedName": "le-gouive",
    "type": "GROWER",
    "city": "Monthelon",
    "address": "8 Rue De Montauban, 51530, Monthelon",
    "region": "Montagne de Reims",
    "description": "Champagne Le Gouive is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-legouive.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/11417742257",
    "initials": "LG",
    "accent": "FF55766F",
    "latitude": 48.9903569,
    "longitude": 3.9315109,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1012736493",
    "name": "Champagne Le Mesnil",
    "normalizedName": "le-mesnil",
    "type": "GROWER",
    "city": "Champagne",
    "address": "19 Rue Charpentier Laurain, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Le Mesnil is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnelemesnil.com/fr/",
    "directoryUrl": "https://www.openstreetmap.org/way/1012736493",
    "initials": "LM",
    "accent": "FF55766F",
    "latitude": 48.9483048,
    "longitude": 4.0224019,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6126819288",
    "name": "Champagne Lepaul",
    "normalizedName": "lepaul",
    "type": "GROWER",
    "city": "Aubilly",
    "address": "9 Rue du Château, 51170, Aubilly",
    "region": "Montagne de Reims",
    "description": "Champagne Lepaul is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/6126819288",
    "initials": "L",
    "accent": "FF55766F",
    "latitude": 49.2123495,
    "longitude": 3.8581629,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11091376985",
    "name": "Champagne Les Cinq Filles",
    "normalizedName": "les-cinq-filles",
    "type": "GROWER",
    "city": "Le Mesnil-sur-Oger",
    "address": "22 Avenue de la République, 51190, Le Mesnil-sur-Oger",
    "region": "Montagne de Reims",
    "description": "Champagne Les Cinq Filles is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://lescinqfilles.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/11091376985",
    "initials": "LC",
    "accent": "FF55766F",
    "latitude": 48.9491207,
    "longitude": 4.0279203,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-358234611",
    "name": "Champagne Marc Hébrart",
    "normalizedName": "marc-hebrart",
    "type": "GROWER",
    "city": "Mareuil-sur-Ay",
    "address": "16 Quai du Moulin, 51160, Mareuil-sur-Ay",
    "region": "Montagne de Reims",
    "description": "Champagne Marc Hébrart is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/358234611",
    "initials": "MH",
    "accent": "FF55766F",
    "latitude": 49.0440545,
    "longitude": 4.0399435,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-476732729",
    "name": "Champagne Marcoult",
    "normalizedName": "marcoult",
    "type": "GROWER",
    "city": "Barbonne-Fayel",
    "address": "12 Route de Queudes, 51120, Barbonne-Fayel",
    "region": "Vallée de la Marne",
    "description": "Champagne Marcoult is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/476732729",
    "initials": "M",
    "accent": "FF55766F",
    "latitude": 48.6568597,
    "longitude": 3.702087,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-12444827932",
    "name": "Champagne Maurice Delabaye et Fils",
    "normalizedName": "maurice-delabaye-et-fils",
    "type": "GROWER",
    "city": "Damery",
    "address": "Rue Anatole France, 51480, Damery",
    "region": "Montagne de Reims",
    "description": "Champagne Maurice Delabaye et Fils is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-delabaye.fr",
    "directoryUrl": "https://www.openstreetmap.org/node/12444827932",
    "initials": "MD",
    "accent": "FF55766F",
    "latitude": 49.0716498,
    "longitude": 3.8808973,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1026416922",
    "name": "Champagne Mennetrier",
    "normalizedName": "mennetrier",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "4 Rue du Champ Bourbon, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Mennetrier is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagne-mennetrier.com/",
    "directoryUrl": "https://www.openstreetmap.org/way/1026416922",
    "initials": "M",
    "accent": "FF55766F",
    "latitude": 48.2613287,
    "longitude": 4.7459136,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6397314886",
    "name": "Champagne Migon-mignon",
    "normalizedName": "migon-mignon",
    "type": "GROWER",
    "city": "Venteuil",
    "address": "9 Route de fleury la riviere, 51480, Venteuil",
    "region": "Montagne de Reims",
    "description": "Champagne Migon-mignon is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-mignon-mignon.fr",
    "directoryUrl": "https://www.openstreetmap.org/node/6397314886",
    "initials": "MM",
    "accent": "FF55766F",
    "latitude": 49.0814829,
    "longitude": 3.856457,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-471507061",
    "name": "Champagne Moët et Chandon",
    "normalizedName": "moet-et-chandon",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Moët et Chandon is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/471507061",
    "initials": "ME",
    "accent": "FF55766F",
    "latitude": 49.0427986,
    "longitude": 3.959082,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9507869235",
    "name": "Champagne Monial",
    "normalizedName": "monial",
    "type": "GROWER",
    "city": "Colombé-le-Sec",
    "address": "Le cellier aux moines, 10200, Colombé-le-Sec",
    "region": "Côte des Bar",
    "description": "Champagne Monial is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.monial.net/",
    "directoryUrl": "https://www.openstreetmap.org/node/9507869235",
    "initials": "M",
    "accent": "FF55766F",
    "latitude": 48.2548665,
    "longitude": 4.7844095,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9483077661",
    "name": "Champagne Nachin Fortini",
    "normalizedName": "nachin-fortini",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "15 Rue de la Fontaine Michelot, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Champagne Nachin Fortini is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.nachin-fortini.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9483077661",
    "initials": "NF",
    "accent": "FF55766F",
    "latitude": 48.262079,
    "longitude": 4.741774,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-931184657",
    "name": "Champagne Perrier Jouët",
    "normalizedName": "perrier-jouet",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Perrier Jouët is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/931184657",
    "initials": "PJ",
    "accent": "FF55766F",
    "latitude": 49.0422706,
    "longitude": 3.9609483,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-636129517",
    "name": "Champagne Pertois-Moriset",
    "normalizedName": "pertois-moriset",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Pertois-Moriset is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/636129517",
    "initials": "PM",
    "accent": "FF55766F",
    "latitude": 48.9485734,
    "longitude": 4.025409,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10758327852",
    "name": "Champagne Philippe Fays",
    "normalizedName": "philippe-fays",
    "type": "GROWER",
    "city": "Celles-sur-Ource",
    "address": "94 Grande Rue, Celles-sur-Ource",
    "region": "Côte des Bar",
    "description": "Champagne Philippe Fays is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-philippefays.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/10758327852",
    "initials": "PF",
    "accent": "FF55766F",
    "latitude": 48.0772615,
    "longitude": 4.392956,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-12395496480",
    "name": "Champagne Philippe Prié",
    "normalizedName": "philippe-prie",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Philippe Prié is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/12395496480",
    "initials": "PP",
    "accent": "FF55766F",
    "latitude": 48.0430369,
    "longitude": 4.4071364,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-6948638155",
    "name": "Champagne Philipponnat",
    "normalizedName": "philipponnat",
    "type": "GROWER",
    "city": "Mareuil-sur-Ay",
    "address": "13 Rue du Pont, 51160, Mareuil-sur-Ay",
    "region": "Montagne de Reims",
    "description": "Champagne Philipponnat is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/6948638155",
    "initials": "P",
    "accent": "FF55766F",
    "latitude": 49.0445134,
    "longitude": 4.040425,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9015404046",
    "name": "Champagne Pierre Launay",
    "normalizedName": "pierre-launay",
    "type": "GROWER",
    "city": "Barbonne-Fayel",
    "address": "11 Rue Saint-Antoine, 51120, Barbonne-Fayel",
    "region": "Vallée de la Marne",
    "description": "Champagne Pierre Launay is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9015404046",
    "initials": "PL",
    "accent": "FF55766F",
    "latitude": 48.6565158,
    "longitude": 3.6978809,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-3471442953",
    "name": "Champagne Pierre Pinard",
    "normalizedName": "pierre-pinard",
    "type": "GROWER",
    "city": "Sézanne",
    "address": "29 Rue Gaston Laplatte, 51120, Sézanne",
    "region": "Vallée de la Marne",
    "description": "Champagne Pierre Pinard is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/3471442953",
    "initials": "PP",
    "accent": "FF55766F",
    "latitude": 48.7270157,
    "longitude": 3.7252819,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-931184656",
    "name": "Champagne Pol Roger",
    "normalizedName": "pol-roger",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Pol Roger is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/931184656",
    "initials": "PR",
    "accent": "FF55766F",
    "latitude": 49.0419031,
    "longitude": 3.9626594,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400007844",
    "name": "Champagne Pouillon Chayoux",
    "normalizedName": "pouillon-chayoux",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Pouillon Chayoux is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400007844",
    "initials": "PC",
    "accent": "FF55766F",
    "latitude": 49.1683999,
    "longitude": 4.0431774,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-476732626",
    "name": "Champagne Prophète And Co",
    "normalizedName": "prophete-and-co",
    "type": "GROWER",
    "city": "Barbonne-Fayel",
    "address": "61 Rue de Lancourt, 51120, Barbonne-Fayel",
    "region": "Vallée de la Marne",
    "description": "Champagne Prophète And Co is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/476732626",
    "initials": "PA",
    "accent": "FF55766F",
    "latitude": 48.6548593,
    "longitude": 3.695132,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9498323114",
    "name": "Champagne René Dosne",
    "normalizedName": "rene-dosne",
    "type": "GROWER",
    "city": "Colombé-le-Sec",
    "address": "26 Rue de Rizaucourt, 10200, Colombé-le-Sec",
    "region": "Côte des Bar",
    "description": "Champagne René Dosne is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-rene-dosne.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/9498323114",
    "initials": "RD",
    "accent": "FF55766F",
    "latitude": 48.2552472,
    "longitude": 4.7978276,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-476732054",
    "name": "Champagne Richomme",
    "normalizedName": "richomme",
    "type": "GROWER",
    "city": "Barbonne-Fayel",
    "address": "6 Rue de la Brèche, 51120, Barbonne-Fayel",
    "region": "Vallée de la Marne",
    "description": "Champagne Richomme is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/476732054",
    "initials": "R",
    "accent": "FF55766F",
    "latitude": 48.6569716,
    "longitude": 3.6931098,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400128405",
    "name": "Champagne Roger Manceaux",
    "normalizedName": "roger-manceaux",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Roger Manceaux is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400128405",
    "initials": "RM",
    "accent": "FF55766F",
    "latitude": 49.1655669,
    "longitude": 4.044955,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10748678714",
    "name": "Champagne Salmon",
    "normalizedName": "salmon",
    "type": "GROWER",
    "city": "Champagne",
    "address": "21-23 Rue du Capitaine Chesnais, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Salmon is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://www.champagnesalmon.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/10748678714",
    "initials": "S",
    "accent": "FF55766F",
    "latitude": 49.1765824,
    "longitude": 3.8601992,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9507869236",
    "name": "Champagne Soret-Devaux",
    "normalizedName": "soret-devaux",
    "type": "GROWER",
    "city": "Colombé-le-Sec",
    "address": "1 Rue de Rizaucourt, 10200, Colombé-le-Sec",
    "region": "Côte des Bar",
    "description": "Champagne Soret-Devaux is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnesoretdevaux.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9507869236",
    "initials": "SD",
    "accent": "FF55766F",
    "latitude": 48.2566351,
    "longitude": 4.7978962,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9505317527",
    "name": "Champagne Tapray Francis",
    "normalizedName": "tapray-francis",
    "type": "GROWER",
    "city": "Colombé-la-Fosse",
    "address": "3 Grande Rue, 10200, Colombé-la-Fosse",
    "region": "Côte des Bar",
    "description": "Champagne Tapray Francis is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9505317527",
    "initials": "TF",
    "accent": "FF55766F",
    "latitude": 48.2617195,
    "longitude": 4.7823269,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-400016350",
    "name": "Champagne Tièche-Morizet",
    "normalizedName": "tieche-morizet",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Tièche-Morizet is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/400016350",
    "initials": "TM",
    "accent": "FF55766F",
    "latitude": 49.1664236,
    "longitude": 4.0444702,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181435873",
    "name": "Champagne Urbain Père et Fils",
    "normalizedName": "urbain-pere-et-fils",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Urbain Père et Fils is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10181435873",
    "initials": "UP",
    "accent": "FF55766F",
    "latitude": 48.190214,
    "longitude": 4.7240545,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-3712378220",
    "name": "Champagne Veuve Marie Blanche Delescaut",
    "normalizedName": "veuve-marie-blanche-delescaut",
    "type": "GROWER",
    "city": "Champagne",
    "address": "50 Rue des Huguenots, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Veuve Marie Blanche Delescaut is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/3712378220",
    "initials": "VM",
    "accent": "FF55766F",
    "latitude": 49.0367922,
    "longitude": 3.9553764,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-13052114867",
    "name": "Champagne Vigreux-Frère",
    "normalizedName": "vigreux-frere",
    "type": "GROWER",
    "city": "Champagne",
    "address": "13 Petite rue, Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Vigreux-Frère is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://champagnevigreuxfrere.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/13052114867",
    "initials": "VF",
    "accent": "FF55766F",
    "latitude": 49.3499528,
    "longitude": 3.9251076,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-3697021307",
    "name": "Champagne Vollereaux",
    "normalizedName": "vollereaux",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Champagne Vollereaux is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-vollereaux.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/3697021307",
    "initials": "V",
    "accent": "FF55766F",
    "latitude": 49.0170271,
    "longitude": 3.9345135,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181435872",
    "name": "Champagne Vuille De la Sagne",
    "normalizedName": "vuille-de-la-sagne",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Vuille De la Sagne is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10181435872",
    "initials": "VD",
    "accent": "FF55766F",
    "latitude": 48.1921443,
    "longitude": 4.7250617,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181435871",
    "name": "Champagne Vuille Didier",
    "normalizedName": "vuille-didier",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Champagne Vuille Didier is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10181435871",
    "initials": "VD",
    "accent": "FF55766F",
    "latitude": 48.1930025,
    "longitude": 4.7212238,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10748636510",
    "name": "Comtesse Lafont",
    "normalizedName": "comtesse-lafont",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Comtesse Lafont is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10748636510",
    "initials": "CL",
    "accent": "FF55766F",
    "latitude": 49.0394062,
    "longitude": 3.9767149,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181435876",
    "name": "Coopérative Barfontarc Champagne Barfontarc",
    "normalizedName": "cooperative-barfontarc-champagne-barfontarc",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Coopérative Barfontarc Champagne Barfontarc is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10181435876",
    "initials": "CB",
    "accent": "FF55766F",
    "latitude": 48.1961798,
    "longitude": 4.7259027,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9483077659",
    "name": "Cooperative Vinicole Arrentières-Engente",
    "normalizedName": "cooperative-vinicole-arrentieres-engente",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "15 Rue Blanche, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Cooperative Vinicole Arrentières-Engente is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/9483077659",
    "initials": "CV",
    "accent": "FF55766F",
    "latitude": 48.2634646,
    "longitude": 4.7410505,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-385375623",
    "name": "Coopérative Vinicole d'Ambonnay",
    "normalizedName": "cooperative-vinicole-d-ambonnay",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Coopérative Vinicole d'Ambonnay is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/385375623",
    "initials": "CV",
    "accent": "FF55766F",
    "latitude": 49.0769675,
    "longitude": 4.1687909,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11417742229",
    "name": "Daniel Champion",
    "normalizedName": "daniel-champion",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Vallée de la Marne",
    "description": "Daniel Champion is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://www.champagne-champion.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/11417742229",
    "initials": "DC",
    "accent": "FF55766F",
    "latitude": 48.8522896,
    "longitude": 3.5979366,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-5723150228",
    "name": "Domaine de Montgrignon",
    "normalizedName": "domaine-de-montgrignon",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Domaine de Montgrignon is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.domaine-montgrignon.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/5723150228",
    "initials": "DD",
    "accent": "FF55766F",
    "latitude": 49.0124674,
    "longitude": 5.6909332,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11323720205",
    "name": "Domaine Eclipse",
    "normalizedName": "domaine-eclipse",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Domaine Eclipse is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/11323720205",
    "initials": "DE",
    "accent": "FF55766F",
    "latitude": 49.5068217,
    "longitude": 5.4742253,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1017360601",
    "name": "Dominique Gauthier Champagne",
    "normalizedName": "dominique-gauthier-champagne",
    "type": "GROWER",
    "city": "Bar-sur-Aube",
    "address": "46 Rue du Général de Gaulle, 10200, Bar-sur-Aube",
    "region": "Côte des Bar",
    "description": "Dominique Gauthier Champagne is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagnegauthierd.com/",
    "directoryUrl": "https://www.openstreetmap.org/way/1017360601",
    "initials": "DG",
    "accent": "FF55766F",
    "latitude": 48.2378275,
    "longitude": 4.7108523,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-12395501143",
    "name": "Famille Moutard",
    "normalizedName": "famille-moutard",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Famille Moutard is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.famillemoutard.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/12395501143",
    "initials": "FM",
    "accent": "FF55766F",
    "latitude": 48.0546312,
    "longitude": 4.3945638,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1278419673",
    "name": "Joseph",
    "normalizedName": "joseph",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Joseph is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/1278419673",
    "initials": "J",
    "accent": "FF55766F",
    "latitude": 49.0779431,
    "longitude": 4.1682651,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-1027048349",
    "name": "Leseurre Gilbert EARL",
    "normalizedName": "leseurre-gilbert-earl",
    "type": "GROWER",
    "city": "Arrentières",
    "address": "3 Rue Blanche, 10200, Arrentières",
    "region": "Côte des Bar",
    "description": "Leseurre Gilbert EARL is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-leseurre.com/",
    "directoryUrl": "https://www.openstreetmap.org/way/1027048349",
    "initials": "LG",
    "accent": "FF55766F",
    "latitude": 48.2609552,
    "longitude": 4.7391739,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9015404047",
    "name": "Maison Marcoult-Guillot",
    "normalizedName": "maison-marcoult-guillot",
    "type": "GROWER",
    "city": "Barbonne-Fayel",
    "address": "28 Grande Rue, 51120, Barbonne-Fayel",
    "region": "Vallée de la Marne",
    "description": "Maison Marcoult-Guillot is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://marcoult-guillot.fr",
    "directoryUrl": "https://www.openstreetmap.org/node/9015404047",
    "initials": "MM",
    "accent": "FF55766F",
    "latitude": 48.6577107,
    "longitude": 3.69531,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-way-391644129",
    "name": "Moet et Chandon Champagne Dom Perignon",
    "normalizedName": "moet-et-chandon-champagne-dom-perignon",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Moet et Chandon Champagne Dom Perignon is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/way/391644129",
    "initials": "ME",
    "accent": "FF55766F",
    "latitude": 49.0814254,
    "longitude": 3.9413282,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-9388308725",
    "name": "Patricia Huguet",
    "normalizedName": "patricia-huguet",
    "type": "GROWER",
    "city": "Bar-sur-Aube",
    "address": "17 Boulevard de la République, 10200, Bar-sur-Aube",
    "region": "Côte des Bar",
    "description": "Patricia Huguet is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-patriciahuguet.com/",
    "directoryUrl": "https://www.openstreetmap.org/node/9388308725",
    "initials": "PH",
    "accent": "FF55766F",
    "latitude": 48.2303886,
    "longitude": 4.7083412,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-11329643866",
    "name": "Poirier du Loup",
    "normalizedName": "poirier-du-loup",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Montagne de Reims",
    "description": "Poirier du Loup is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/11329643866",
    "initials": "PD",
    "accent": "FF55766F",
    "latitude": 49.5072969,
    "longitude": 5.4759074,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-10181435874",
    "name": "Pressoir Champagne Vuille De la Sagne et Champagne Didier Vuille",
    "normalizedName": "pressoir-champagne-vuille-de-la-sagne-et-champagne-didier-vuille",
    "type": "GROWER",
    "city": "Champagne",
    "address": "Champagne",
    "region": "Côte des Bar",
    "description": "Pressoir Champagne Vuille De la Sagne et Champagne Didier Vuille is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "",
    "directoryUrl": "https://www.openstreetmap.org/node/10181435874",
    "initials": "PC",
    "accent": "FF55766F",
    "latitude": 48.1932445,
    "longitude": 4.722622,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-5904615536",
    "name": "Vigneron Bernard Naude",
    "normalizedName": "vigneron-bernard-naude",
    "type": "GROWER",
    "city": "Charly-sur-Marne",
    "address": "12 Avenue Fernand Drouet, 02310, Charly-sur-Marne",
    "region": "Vallée de la Marne",
    "description": "Vigneron Bernard Naude is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "https://www.champagne-bernard-naude.com",
    "directoryUrl": "https://www.openstreetmap.org/node/5904615536",
    "initials": "VB",
    "accent": "FF55766F",
    "latitude": 48.9758778,
    "longitude": 3.2992986,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  },
  {
    "id": "osm-node-5904718524",
    "name": "Vigneron Châtelain",
    "normalizedName": "vigneron-chatelain",
    "type": "GROWER",
    "city": "Charly-sur-Marne",
    "address": "3 Rue des Glauriettes, 02310, Charly-sur-Marne",
    "region": "Vallée de la Marne",
    "description": "Vigneron Châtelain is als wijnproducent of champagnehuis opgenomen in OpenStreetMap.",
    "website": "http://champagne-chatelain.fr/",
    "directoryUrl": "https://www.openstreetmap.org/node/5904718524",
    "initials": "VC",
    "accent": "FF55766F",
    "latitude": 48.9603808,
    "longitude": 3.2604654,
    "sourceIds": [
      "openstreetmap"
    ],
    "sourceUpdatedAt": "2026-07-24"
  }
];
