import { NotFound, VersionConflict } from "./slice2-store.mjs";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,HOUSE=/^[a-z0-9][a-z0-9-]{0,199}$/;
export const BADGE_RULES_VERSION=1;
class ApiError extends Error{constructor(status,code,message,details){super(message);Object.assign(this,{status,code,details});}}
async function body(req){const parts=[];let n=0;for await(const p of req){n+=p.length;if(n>262144)throw new ApiError(413,"PAYLOAD_TOO_LARGE","Request body is too large");parts.push(p);}if(!parts.length)return{};try{return JSON.parse(Buffer.concat(parts));}catch{throw new ApiError(400,"INVALID_JSON","Request body must be valid JSON");}}
const uid=(v,n)=>{v=String(v||"");if(!UUID.test(v))throw new ApiError(400,"INVALID_FIELD",`${n} must be a UUID`,{field:n});return v.toLowerCase();};
const hid=v=>{v=String(v||"");if(!HOUSE.test(v))throw new ApiError(400,"INVALID_FIELD","houseId is invalid",{field:"houseId"});return v;};
const ts=(v,n,nullable=false)=>{if(nullable&&(v==null||v===""))return null;const d=new Date(v);if(!v||isNaN(d))throw new ApiError(400,"INVALID_FIELD",`${n} must be ISO-8601`,{field:n});return d.toISOString();};
const cursor=()=>new Date().toISOString();
function tripInput(x,create=false){const o={};if(create)o.clientGeneratedId=uid(x.clientGeneratedId,"clientGeneratedId");if(create||x.name!==undefined){o.name=String(x.name||"").trim();if(!o.name||o.name.length>120)throw new ApiError(400,"INVALID_FIELD","name is required",{field:"name"});}for(const k of["startDate","endDate"])if(x[k]!==undefined){if(x[k]!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(x[k]))throw new ApiError(400,"INVALID_FIELD",`${k} must be YYYY-MM-DD`);o[k]=x[k];}if(x.notes!==undefined)o.notes=String(x.notes||"").slice(0,4000);if(x.status!==undefined){if(!["DRAFT","PLANNED","COMPLETED"].includes(x.status))throw new ApiError(400,"INVALID_FIELD","Invalid trip status");o.status=x.status;}if(create)o.idempotencyKey=uid(x.idempotencyKey,"idempotencyKey");else{o.version=Number(x.version);if(!Number.isInteger(o.version)||o.version<1)throw new ApiError(400,"INVALID_FIELD","version must be positive");}return o;}
function itemInput(x,create=false){const o={};if(create)o.clientGeneratedId=uid(x.clientGeneratedId,"clientGeneratedId");if(create||x.houseId!==undefined)o.houseId=hid(x.houseId);if(create||x.position!==undefined){o.position=Number(x.position);if(!Number.isInteger(o.position)||o.position<0)throw new ApiError(400,"INVALID_FIELD","position is invalid");}if(x.plannedArrival!==undefined)o.plannedArrival=ts(x.plannedArrival,"plannedArrival",true);if(x.durationMinutes!==undefined){o.durationMinutes=x.durationMinutes==null?null:Number(x.durationMinutes);if(o.durationMinutes!==null&&(!Number.isInteger(o.durationMinutes)||o.durationMinutes<1||o.durationMinutes>1440))throw new ApiError(400,"INVALID_FIELD","durationMinutes is invalid");}if(x.notes!==undefined)o.notes=String(x.notes||"").slice(0,4000);if(x.status!==undefined){if(!["PLANNED","VISITED","SKIPPED"].includes(x.status))throw new ApiError(400,"INVALID_FIELD","Invalid item status");o.status=x.status;}if(create)o.idempotencyKey=uid(x.idempotencyKey,"idempotencyKey");else{o.version=Number(x.version);if(!Number.isInteger(o.version)||o.version<1)throw new ApiError(400,"INVALID_FIELD","version must be positive");}return o;}
const radians=n=>n*Math.PI/180;
function distance(a,b){const dlat=radians(b.latitude-a.latitude),dlon=radians(b.longitude-a.longitude),q=Math.sin(dlat/2)**2+Math.cos(radians(a.latitude))*Math.cos(radians(b.latitude))*Math.sin(dlon/2)**2;return Math.round(12742000*Math.asin(Math.sqrt(q)));}
function proposal(trip,x,catalog){const ids=(x.itemIds||trip.items.map(i=>i.id)).map(v=>uid(v,"itemIds")),items=ids.map(id=>trip.items.find(i=>i.id===id));if(items.some(v=>!v))throw new ApiError(400,"UNKNOWN_TRIP_ITEM","Every itemId must belong to the trip");const houses=new Map(catalog.map(h=>[h.id,h])),warnings=[],legs=[];items.forEach(i=>{const h=houses.get(i.houseId);if(!Number.isFinite(h?.latitude)||!Number.isFinite(h?.longitude))warnings.push({code:"MISSING_COORDINATES",severity:"WARNING",message:"Geen coördinaten beschikbaar; controleer deze stop handmatig.",houseId:i.houseId,itemId:i.id});});let totalDistanceMeters=0;for(let i=1;i<items.length;i++){const a=houses.get(items[i-1].houseId),b=houses.get(items[i].houseId);if(Number.isFinite(a?.latitude)&&Number.isFinite(b?.latitude)){const d=distance(a,b),seconds=Math.round(d/13.89);totalDistanceMeters+=d;legs.push({fromItemId:items[i-1].id,toItemId:items[i].id,distanceMeters:d,durationSeconds:seconds});}}return{tripId:trip.id,generatedAt:cursor(),orderedItemIds:ids,totalDistanceMeters,totalDurationSeconds:legs.reduce((s,l)=>s+l.durationSeconds,0),legs,warnings,calculation:"STRAIGHT_LINE_ESTIMATE",mutatedTripOrder:false};}
export function buildJourney(raw,catalog){const totals=new Map();catalog.forEach(h=>{if(h.region)totals.set(h.region,(totals.get(h.region)||0)+1);});const visited=new Set(raw.visits.map(v=>v.houseId));const regionProgress=[...totals].map(([regionId,totalHouseCount])=>({regionId,totalHouseCount,visitedHouseCount:catalog.filter(h=>h.region===regionId&&visited.has(h.id)).length}));return{generatedAt:cursor(),stats:{visitedHouseCount:visited.size,savedHouseCount:raw.savedHouseIds.length,tripCount:raw.trips.length,completedTripCount:raw.trips.filter(t=>t.status==="COMPLETED").length,regionsStarted:regionProgress.filter(r=>r.visitedHouseCount).length,regionsCompleted:regionProgress.filter(r=>r.totalHouseCount&&r.visitedHouseCount===r.totalHouseCount).length},regionProgress,visited:raw.visits.map(({clientVisitId,houseId,visitedAt,tripId})=>({clientVisitId,houseId,visitedAt,tripId})),savedHouseIds:raw.savedHouseIds};}
export function evaluateBadges(journey,version=1,at=cursor()){if(version!==1)throw new ApiError(400,"UNSUPPORTED_RULES_VERSION","Unsupported badge rules version",{supported:[1]});const specs=[["first-visit","Eerste bezoek","Bezoek je eerste huis",journey.stats.visitedHouseCount,1],["ten-houses","Champagneliefhebber","Bezoek 10 huizen",journey.stats.visitedHouseCount,10],["twenty-houses","Ontdekkingsreiziger","Bezoek 20 huizen",journey.stats.visitedHouseCount,20],["all-regions-started","Alle regio’s gestart","Bezoek één huis in iedere regio",journey.stats.regionsStarted,journey.regionProgress.length]];journey.regionProgress.forEach(r=>specs.push([`region-${r.regionId}`,`${r.regionId} compleet`,`Bezoek alle huizen in deze regio`,r.visitedHouseCount,r.totalHouseCount,{regionId:r.regionId}]));return specs.map(([badgeId,title,description,current,target,metadata={}])=>({badgeId,ruleVersion:version,title,description,state:target>0&&current>=target?"UNLOCKED":current>0?"IN_PROGRESS":"LOCKED",current,target,unlockedAt:target>0&&current>=target?at:null,metadata}));}

export async function handleSlice2({request,response,url,user,store,send,catalog,limits={}}){if(!/^\/api\/v1\/(user-saved-houses|trips|visits|journey|badge-progress)(\/|$)/.test(url.pathname))return false;if(!user){send(response,401,{error:{code:"AUTH_REQUIRED",message:"Authentication required"}});return true;}try{
 if(url.pathname==="/api/v1/user-saved-houses"&&request.method==="GET"){send(response,200,{items:await store.savedHouses(user.sub),syncCursor:cursor()});return true;}
 let m=url.pathname.match(/^\/api\/v1\/user-saved-houses\/([a-z0-9-]+)$/);if(m&&request.method==="PUT"){const x=await body(request);if(typeof x.saved!=="boolean")throw new ApiError(400,"INVALID_FIELD","saved must be boolean");const houseId=hid(m[1]);if(x.saved&&Number.isFinite(limits.favoriteHouses)){const active=await store.savedHouses(user.sub);if(!active.some(item=>item.houseId===houseId)&&active.length>=limits.favoriteHouses)throw new ApiError(402,"ENTITLEMENT_REQUIRED",`Je limiet van ${limits.favoriteHouses} favoriete huizen is bereikt`,{feature:"MORE_FAVORITE_HOUSES"});}send(response,200,await store.setSavedHouse(user.sub,houseId,{saved:x.saved,idempotencyKey:uid(x.idempotencyKey,"idempotencyKey"),clientUpdatedAt:ts(x.clientUpdatedAt,"clientUpdatedAt")}));return true;}
 if(url.pathname==="/api/v1/trips"&&request.method==="GET"){send(response,200,{items:await store.trips(user.sub,url.searchParams.get("includeItems")==="true"),syncCursor:cursor()});return true;}
 if(url.pathname==="/api/v1/trips"&&request.method==="POST"){send(response,201,await store.createTrip(user.sub,tripInput(await body(request),true)));return true;}
 m=url.pathname.match(/^\/api\/v1\/trips\/([0-9a-f-]+)$/i);if(m&&request.method==="GET"){send(response,200,await store.trip(user.sub,uid(m[1],"tripId")));return true;}if(m&&request.method==="PATCH"){send(response,200,await store.updateTrip(user.sub,uid(m[1],"tripId"),tripInput(await body(request))));return true;}if(m&&request.method==="DELETE"){const x=await body(request);send(response,200,await store.deleteTrip(user.sub,uid(m[1],"tripId"),Number(x.version)));return true;}
 m=url.pathname.match(/^\/api\/v1\/trips\/([0-9a-f-]+)\/items$/i);if(m&&request.method==="POST"){send(response,201,await store.createItem(user.sub,uid(m[1],"tripId"),itemInput(await body(request),true)));return true;}
 m=url.pathname.match(/^\/api\/v1\/trips\/([0-9a-f-]+)\/items\/order$/i);if(m&&request.method==="PUT"){const x=await body(request);if(!Array.isArray(x.itemIds))throw new ApiError(400,"INVALID_FIELD","itemIds must be an array");send(response,200,await store.reorderItems(user.sub,uid(m[1],"tripId"),x.itemIds.map(i=>uid(i,"itemIds")),Number(x.version)));return true;}
 m=url.pathname.match(/^\/api\/v1\/trips\/([0-9a-f-]+)\/items\/([0-9a-f-]+)$/i);if(m&&request.method==="PATCH"){send(response,200,await store.updateItem(user.sub,uid(m[1],"tripId"),uid(m[2],"itemId"),itemInput(await body(request))));return true;}if(m&&request.method==="DELETE"){const x=await body(request);send(response,200,await store.deleteItem(user.sub,uid(m[1],"tripId"),uid(m[2],"itemId"),Number(x.version)));return true;}
 m=url.pathname.match(/^\/api\/v1\/trips\/([0-9a-f-]+)\/route-proposal$/i);if(m&&request.method==="POST"){if(limits.smartTripPlanning===false)throw new ApiError(402,"ENTITLEMENT_REQUIRED","Slimme reisplanning vereist Pro, Pro Plus of een Trip Pass",{feature:"ROUTE_OPTIMIZATION"});const tripId=uid(m[1],"tripId"),x=await body(request),key=uid(x.idempotencyKey,"idempotencyKey");if(x.travelMode!=="DRIVING")throw new ApiError(400,"INVALID_FIELD","Only DRIVING is supported");const out=proposal(await store.trip(user.sub,tripId),x,catalog);send(response,200,await store.saveRouteProposal(user.sub,tripId,key,x,out));return true;}
 if(url.pathname==="/api/v1/visits"&&request.method==="GET"){const all=await store.visits(user.sub,url.searchParams.get("changedSince"));send(response,200,{items:all.filter(v=>!v.deletedAt),tombstones:all.filter(v=>v.deletedAt).map(v=>({clientVisitId:v.clientVisitId,deletedAt:v.deletedAt})),syncCursor:cursor()});return true;}
 m=url.pathname.match(/^\/api\/v1\/visits\/([0-9a-f-]+)$/i);if(m&&request.method==="PUT"){const id=uid(m[1],"clientVisitId"),x=await body(request);if(x.clientVisitId&&uid(x.clientVisitId,"clientVisitId")!==id)throw new ApiError(400,"INVALID_FIELD","Path and body clientVisitId differ");if(!["MANUAL","TRIP"].includes(x.source))throw new ApiError(400,"INVALID_FIELD","Invalid source");const input={houseId:hid(x.houseId),visitedAt:ts(x.visitedAt,"visitedAt"),timezoneOffsetMinutes:Number(x.timezoneOffsetMinutes||0),source:x.source,tripId:x.tripId?uid(x.tripId,"tripId"):null,tripItemId:x.tripItemId?uid(x.tripItemId,"tripItemId"):null,idempotencyKey:uid(x.idempotencyKey,"idempotencyKey"),clientUpdatedAt:ts(x.clientUpdatedAt,"clientUpdatedAt")};if(!Number.isInteger(input.timezoneOffsetMinutes)||Math.abs(input.timezoneOffsetMinutes)>840)throw new ApiError(400,"INVALID_FIELD","Invalid timezone offset");if(input.source==="TRIP"&&!input.tripId)throw new ApiError(400,"INVALID_FIELD","tripId required for TRIP");send(response,200,await store.putVisit(user.sub,id,input));return true;}if(m&&request.method==="DELETE"){await body(request);send(response,200,await store.deleteVisit(user.sub,uid(m[1],"clientVisitId")));return true;}
 if(url.pathname==="/api/v1/journey"&&request.method==="GET"){send(response,200,buildJourney(await store.journeyData(user.sub),catalog));return true;}
 if(url.pathname==="/api/v1/badge-progress"&&request.method==="GET"){const v=Number(url.searchParams.get("rulesVersion")||1),at=cursor(),journey=buildJourney(await store.journeyData(user.sub),catalog),badges=evaluateBadges(journey,v,at);await store.saveBadges(user.sub,v,badges,at);send(response,200,{rulesVersion:v,evaluatedAt:at,badges});return true;}
 send(response,405,{error:{code:"METHOD_NOT_ALLOWED",message:"Method not allowed"}});return true;
}catch(e){if(e instanceof VersionConflict)send(response,409,{error:{code:"VERSION_CONFLICT",message:"The object has changed",details:{serverVersion:e.serverVersion}}});else if(e instanceof NotFound)send(response,404,{error:{code:"NOT_FOUND",message:e.message}});else if(e instanceof ApiError)send(response,e.status,{error:{code:e.code,message:e.message,...(e.details?{details:e.details}:{})}});else{console.error("Slice 2 request failed:",e.message);send(response,400,{error:{code:"INVALID_REQUEST",message:e.message||"Invalid request"}});}return true;}}
