import { randomUUID } from "node:crypto";
import pg from "pg";

let pool;
const iso=v=>v?new Date(v).toISOString():null;
const clean=row=>Object.fromEntries(Object.entries(row).filter(([k])=>!k.startsWith("_")&&k!=="user_id"));
const mapKeys=(row)=>clean({id:row.id,clientGeneratedId:row.client_generated_id,tripId:row.trip_id,houseId:row.house_id,
 position:row.position,plannedArrival:iso(row.planned_arrival),durationMinutes:row.duration_minutes,notes:row.notes,status:row.status,
 version:row.version,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),deletedAt:iso(row.deleted_at)});
const tripDto=(r,items=[])=>({id:r.id,clientGeneratedId:r.client_generated_id,name:r.name,startDate:r.start_date?String(r.start_date).slice(0,10):null,
 endDate:r.end_date?String(r.end_date).slice(0,10):null,notes:r.notes,status:r.status,version:r.version,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at),deletedAt:iso(r.deleted_at),items});
const visitDto=r=>({id:r.id,clientVisitId:r.client_visit_id,houseId:r.house_id,visitedAt:iso(r.visited_at),timezoneOffsetMinutes:r.timezone_offset_minutes,
 source:r.source,tripId:r.trip_id,tripItemId:r.trip_item_id,clientUpdatedAt:iso(r.client_updated_at),createdAt:iso(r.created_at),updatedAt:iso(r.updated_at),deletedAt:iso(r.deleted_at)});

export class NotFound extends Error{}
export class VersionConflict extends Error{constructor(serverVersion){super("Version conflict");this.serverVersion=serverVersion;}}

function db(){
 const url=String(process.env.DATABASE_URL||"").trim();if(!url)throw new Error("DATABASE_URL is required");
 const sslOff=["0","false","disable"].includes(String(process.env.DATABASE_SSL||"").toLowerCase())||url.includes("localhost");
 return pool ||= new pg.Pool({connectionString:url,ssl:sslOff?false:{rejectUnauthorized:false}});
}
async function ownedTrip(q,user,id,deleted=false){const r=(await q.query(`SELECT * FROM user_trips WHERE id=$1 AND user_id=$2 ${deleted?"":"AND deleted_at IS NULL"}`,[id,user])).rows[0];if(!r)throw new NotFound("Trip not found");return r;}

export class Slice2Store{
 async savedHouses(user){return(await db().query(`SELECT house_id,saved,saved_at,updated_at,deleted_at FROM user_saved_houses WHERE user_id=$1 AND saved AND deleted_at IS NULL ORDER BY saved_at`,[user])).rows.map(r=>({houseId:r.house_id,saved:r.saved,savedAt:iso(r.saved_at),updatedAt:iso(r.updated_at),deletedAt:iso(r.deleted_at)}));}
 async setSavedHouse(user,house,input){const r=(await db().query(`INSERT INTO user_saved_houses(user_id,house_id,saved,idempotency_key,client_updated_at,deleted_at)VALUES($1,$2,$3,$4,$5,CASE WHEN $3 THEN NULL ELSE NOW() END)
 ON CONFLICT(user_id,house_id)DO UPDATE SET saved=EXCLUDED.saved,idempotency_key=COALESCE(user_saved_houses.idempotency_key,EXCLUDED.idempotency_key),client_updated_at=EXCLUDED.client_updated_at,
 updated_at=CASE WHEN user_saved_houses.idempotency_key=EXCLUDED.idempotency_key THEN user_saved_houses.updated_at ELSE NOW() END,deleted_at=CASE WHEN EXCLUDED.saved THEN NULL ELSE COALESCE(user_saved_houses.deleted_at,NOW()) END RETURNING *`,[user,house,input.saved,input.idempotencyKey,input.clientUpdatedAt])).rows[0];return{houseId:r.house_id,saved:r.saved,savedAt:iso(r.saved_at),updatedAt:iso(r.updated_at),deletedAt:iso(r.deleted_at)};}
 async trips(user,include=false){const q=db(),trips=(await q.query(`SELECT * FROM user_trips WHERE user_id=$1 AND deleted_at IS NULL ORDER BY created_at`,[user])).rows,items=include?(await q.query(`SELECT * FROM user_trip_items WHERE user_id=$1 AND deleted_at IS NULL ORDER BY position`,[user])).rows:[];return trips.map(t=>tripDto(t,items.filter(i=>i.trip_id===t.id).map(mapKeys)));}
 async trip(user,id){const q=db(),t=await ownedTrip(q,user,id),items=(await q.query(`SELECT * FROM user_trip_items WHERE user_id=$1 AND trip_id=$2 AND deleted_at IS NULL ORDER BY position`,[user,id])).rows.map(mapKeys);return tripDto(t,items);}
 async createTrip(user,x){const r=(await db().query(`INSERT INTO user_trips(id,user_id,client_generated_id,name,start_date,end_date,notes,status,idempotency_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
 ON CONFLICT(user_id,client_generated_id)DO UPDATE SET client_generated_id=EXCLUDED.client_generated_id RETURNING *`,[randomUUID(),user,x.clientGeneratedId,x.name,x.startDate,x.endDate,x.notes||"",x.status||"DRAFT",x.idempotencyKey])).rows[0];return tripDto(r);}
 async updateTrip(user,id,x){const q=db(),old=await ownedTrip(q,user,id);if(old.version!==x.version)throw new VersionConflict(old.version);const r=(await q.query(`UPDATE user_trips SET name=COALESCE($3,name),start_date=COALESCE($4,start_date),end_date=COALESCE($5,end_date),notes=COALESCE($6,notes),status=COALESCE($7,status),version=version+1,updated_at=NOW() WHERE id=$1 AND user_id=$2 AND version=$8 RETURNING *`,[id,user,x.name,x.startDate,x.endDate,x.notes,x.status,x.version])).rows[0];if(!r)throw new VersionConflict((await ownedTrip(q,user,id)).version);return tripDto(r);}
 async deleteTrip(user,id,version){const q=db(),old=await ownedTrip(q,user,id,true);if(old.deleted_at)return tripDto(old);if(old.version!==version)throw new VersionConflict(old.version);return tripDto((await q.query(`UPDATE user_trips SET deleted_at=NOW(),updated_at=NOW(),version=version+1 WHERE id=$1 AND user_id=$2 RETURNING *`,[id,user])).rows[0]);}
 async createItem(user,trip,x){const q=db();await ownedTrip(q,user,trip);const r=(await q.query(`INSERT INTO user_trip_items(id,user_id,trip_id,client_generated_id,house_id,position,planned_arrival,duration_minutes,notes,status,idempotency_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
 ON CONFLICT(user_id,client_generated_id)DO UPDATE SET client_generated_id=EXCLUDED.client_generated_id RETURNING *`,[randomUUID(),user,trip,x.clientGeneratedId,x.houseId,x.position,x.plannedArrival,x.durationMinutes,x.notes||"",x.status||"PLANNED",x.idempotencyKey])).rows[0];return mapKeys(r);}
 async updateItem(user,trip,id,x){const q=db();await ownedTrip(q,user,trip);const old=(await q.query(`SELECT * FROM user_trip_items WHERE id=$1 AND trip_id=$2 AND user_id=$3 AND deleted_at IS NULL`,[id,trip,user])).rows[0];if(!old)throw new NotFound("Trip item not found");if(old.version!==x.version)throw new VersionConflict(old.version);return mapKeys((await q.query(`UPDATE user_trip_items SET house_id=COALESCE($4,house_id),position=COALESCE($5,position),planned_arrival=COALESCE($6,planned_arrival),duration_minutes=COALESCE($7,duration_minutes),notes=COALESCE($8,notes),status=COALESCE($9,status),version=version+1,updated_at=NOW() WHERE id=$1 AND trip_id=$2 AND user_id=$3 RETURNING *`,[id,trip,user,x.houseId,x.position,x.plannedArrival,x.durationMinutes,x.notes,x.status])).rows[0]);}
 async deleteItem(user,trip,id,version){const q=db();await ownedTrip(q,user,trip);const old=(await q.query(`SELECT * FROM user_trip_items WHERE id=$1 AND trip_id=$2 AND user_id=$3`,[id,trip,user])).rows[0];if(!old)throw new NotFound("Trip item not found");if(old.deleted_at)return mapKeys(old);if(old.version!==version)throw new VersionConflict(old.version);return mapKeys((await q.query(`UPDATE user_trip_items SET deleted_at=NOW(),updated_at=NOW(),version=version+1 WHERE id=$1 AND user_id=$2 RETURNING *`,[id,user])).rows[0]);}
 async reorderItems(user,trip,ids,version){const q=db(),client=await q.connect();try{await client.query("BEGIN");const t=await ownedTrip(client,user,trip);if(t.version!==version)throw new VersionConflict(t.version);const owned=(await client.query(`SELECT id FROM user_trip_items WHERE user_id=$1 AND trip_id=$2 AND deleted_at IS NULL`,[user,trip])).rows.map(r=>r.id);if(owned.length!==ids.length||owned.some(id=>!ids.includes(id)))throw new Error("Order must contain all active items");for(let p=0;p<ids.length;p++)await client.query(`UPDATE user_trip_items SET position=$4,version=version+1,updated_at=NOW() WHERE id=$1 AND trip_id=$2 AND user_id=$3`,[ids[p],trip,user,p]);await client.query(`UPDATE user_trips SET version=version+1,updated_at=NOW() WHERE id=$1 AND user_id=$2`,[trip,user]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}return this.trip(user,trip);}
 async saveRouteProposal(user,trip,key,request,response){const q=db();await ownedTrip(q,user,trip);return(await q.query(`INSERT INTO user_trip_route_proposals(id,user_id,trip_id,idempotency_key,request_json,response_json)VALUES($1,$2,$3,$4,$5,$6)ON CONFLICT(user_id,idempotency_key)DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING response_json`,[randomUUID(),user,trip,key,request,response])).rows[0].response_json;}
 async visits(user,since){return(await db().query(`SELECT * FROM user_visit_events WHERE user_id=$1 AND($2::timestamptz IS NULL OR updated_at>$2)ORDER BY updated_at`,[user,since||null])).rows.map(visitDto);}
 async putVisit(user,id,x){const r=(await db().query(`INSERT INTO user_visit_events(id,user_id,client_visit_id,house_id,visited_at,timezone_offset_minutes,source,trip_id,trip_item_id,idempotency_key,client_updated_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)ON CONFLICT(user_id,client_visit_id)DO UPDATE SET client_visit_id=EXCLUDED.client_visit_id RETURNING *`,[randomUUID(),user,id,x.houseId,x.visitedAt,x.timezoneOffsetMinutes,x.source,x.tripId,x.tripItemId,x.idempotencyKey,x.clientUpdatedAt])).rows[0];return visitDto(r);}
 async deleteVisit(user,id){const r=(await db().query(`UPDATE user_visit_events SET deleted_at=COALESCE(deleted_at,NOW()),updated_at=CASE WHEN deleted_at IS NULL THEN NOW() ELSE updated_at END WHERE user_id=$1 AND client_visit_id=$2 RETURNING *`,[user,id])).rows[0];if(!r)throw new NotFound("Visit not found");return visitDto(r);}
 async journeyData(user){const q=db(),[v,s,t]=await Promise.all([q.query(`SELECT DISTINCT ON(house_id)* FROM user_visit_events WHERE user_id=$1 AND deleted_at IS NULL ORDER BY house_id,visited_at DESC NULLS LAST,created_at`,[user]),q.query(`SELECT house_id FROM user_saved_houses WHERE user_id=$1 AND saved AND deleted_at IS NULL`,[user]),q.query(`SELECT id,status FROM user_trips WHERE user_id=$1 AND deleted_at IS NULL`,[user])]);return{visits:v.rows.map(visitDto),savedHouseIds:s.rows.map(r=>r.house_id),trips:t.rows};}
 async saveBadges(user,version,badges,at){const q=db(),c=await q.connect();try{await c.query("BEGIN");for(const b of badges)await c.query(`INSERT INTO user_badge_progress(user_id,badge_id,rules_version,state,current_value,target_value,unlocked_at,metadata,evaluated_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)ON CONFLICT(user_id,badge_id,rules_version)DO UPDATE SET state=EXCLUDED.state,current_value=EXCLUDED.current_value,target_value=EXCLUDED.target_value,unlocked_at=COALESCE(user_badge_progress.unlocked_at,EXCLUDED.unlocked_at),metadata=EXCLUDED.metadata,evaluated_at=EXCLUDED.evaluated_at`,[user,b.badgeId,version,b.state,b.current,b.target,b.unlockedAt,b.metadata||{},at]);await c.query("COMMIT");}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
}
let singleton;export const slice2Store=()=>singleton||=(new Slice2Store());
